### ISSUE TITLE
BUG: Data Output Data Range boxes not working

### ISSUE THREAD

**Issue by LucyJordan** [UGS-GIO/groundwaterMonPortal#40]
### What happened?

1. Select a well from the map
2. Click Get details
3. Change dates in the Data Output Date Range boxes.
4. Click download.

### What did you expect to happen?

![image](https://user-images.githubusercontent.com/117779550/200682562-5c16c26b-7e1b-4c0c-86cd-f661e75b4342.png)

1. I would like to downloaded file to be data for the range I entered into the Data Output Date Range  boxes. Instead, the downloaded csv file seems to be downloading approximately the data showing up on the graph, regardless of what date I enter into the boxes. While this is just annoying for most wells because I have to click Show All on the graph and then try to use the slider to get the graph to display somewhere close to the range I want to download, I cannot get the graph to show all the data back to 2012 for CHWENT well number 138 384149109400902, so there is no way to download data earlier than Oct 2019. 

### Browser Version

chrome Version 107.0.5304.88 (Official Build) (64-bit)

**Comment by marshallrobinson** [comment]
I get the same results. Thanks for submitting.
@marthajensen, will you please confirm that CHWENT only has data in the database for the dates that are getting displayed in the chart?

**Comment by marthajensen** [comment]
@LucyJordan 

I am in contact with Paul about this issue and I'll get back to you

**Comment by lance-weaver** [comment]
This should be fixed...

**Comment by marshallrobinson** [comment]
Thanks for working on this, Lance.

Here's the current status:
-The downloaded CSV respects the date entered in the Data Output Date Range boxes.
-The data before 2019 is getting worked out with Martha and Paul.

**Comment by LucyJordan** [comment]
I talked to Paul yesterday and the data before 2019 for CHWENT is not in
the database for quality control reasons.

Thanks,
Lucy

**Comment by LucyJordan** [comment]
I just tested CHWNVJ trying to download Daily and All. I am still having the problem that the date I type into the boxes is not the date that I get downloaded.

**Comment by marshallrobinson** [comment]
That's interesting. I wonder if you are still seeing an old-version of the application. Try pressing ctrl+shift+r to get the newest version of the app and then retry those downloads.

**Comment by LucyJordan** [comment]
That worked! I swear I cleared my cache before I tried it again, but I used
a different command than ctrl shift r and that did not do the trick.

Thanks!
Lucy
